#
# (c)2024 Wolverine Radar Company. All rights reserved.
#

version: "3.9"

services:

  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
      - ./server/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./server/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../certbot/conf:/etc/letsencrypt
      - ../certbot/www:/var/www/certbot
    ports:
      - "80:80"
    restart: unless-stopped
    command: /bin/sh -c "while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g 'daemon off;'"

  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - ../certbot/conf:/etc/letsencrypt
      - ../certbot/www:/var/www/certbot
    restart: unless-stopped
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;"
    depends_on:
      - nginx
      
  
#
# (c)2024 Wolverine Radar Company. All rights reserved.
#
